# Generated by Django 4.2.7 on 2025-08-03 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "email_campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "content",
                    models.TextField(
                        help_text="Template content with placeholders like {first_name}, {company_name}, etc."
                    ),
                ),
                (
                    "offering",
                    models.CharField(
                        choices=[
                            ("cs3_system", "Cerebras CS-3 System"),
                            ("condor_galaxy", "Cerebras Condor Galaxy"),
                            ("ai_inference", "Cerebras AI Inference Solution"),
                            ("inference_api", "Cerebras Inference API"),
                            ("model_studio", "Cerebras AI Model Studio"),
                            ("datacenter_rental", "Cerebras Datacenter Rental"),
                        ],
                        help_text="Which Cerebras offering this template is designed for",
                        max_length=100,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a default system template",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of when to use this template",
                        null=True,
                    ),
                ),
                (
                    "subject_line",
                    models.CharField(
                        help_text="Email subject line template", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "email_templates",
                "ordering": ["offering", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmailDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_line", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("reviewed", "Reviewed"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_send_date", models.DateTimeField(blank=True, null=True)),
                ("sent_date", models.DateTimeField(blank=True, null=True)),
                ("follow_up_date", models.DateTimeField(blank=True, null=True)),
                (
                    "personalization_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "recommended_offering",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="outreach.emailcampaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_drafts",
                        to="companies.contact",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="outreach.emailtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "email_drafts",
                "ordering": ["-created_at"],
                "unique_together": {("contact", "campaign")},
            },
        ),
    ]
