# Generated by Django 4.2.7 on 2025-08-03 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaildraft",
            name="follow_up_scheduled",
            field=models.BooleanField(
                default=False, help_text="Whether a follow-up email is scheduled"
            ),
        ),
        migrations.AddField(
            model_name="emaildraft",
            name="follow_up_sent",
            field=models.BooleanField(
                default=False, help_text="Whether the follow-up has been sent"
            ),
        ),
        migrations.AddField(
            model_name="emaildraft",
            name="follow_up_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template to use for follow-up",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="follow_up_drafts",
                to="outreach.emailtemplate",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[("initial", "Initial Outreach"), ("follow_up", "Follow-up")],
                default="initial",
                help_text="Whether this is an initial outreach or follow-up template",
                max_length=20,
            ),
        ),
    ]
