# Generated by Django 4.2.7 on 2025-08-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='linkedin_profile_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
